import { APP_PREFIX_PATH } from 'constants/route.constant'
import {
    NAV_ITEM_TYPE_TITLE,
    NAV_ITEM_TYPE_COLLAPSE,
    NAV_ITEM_TYPE_ITEM,
} from 'constants/navigation.constant'
import { ADMIN, USER } from 'constants/roles.constant'

const appsNavigationConfig = [
    {
        // key: 'apps',
        path: '',
        // title: 'APPS',
        translateKey: 'nav.apps',
        // icon: 'apps',
        type: NAV_ITEM_TYPE_TITLE,
        authority: [ADMIN, USER],
        subMenu: [
           
            {
                key: 'appsSales.dashboard',
                path: `${APP_PREFIX_PATH}/sales/dashboard`,
                title: 'Dashboard',
                translateKey: 'nav.appsSales.dashboard',
                icon: 'sales',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [USER],
                subMenu: [],
            },

            {
                key: 'Shipments',
                path: '',
                title: 'Shipments',
                translateKey: 'nav.Shipments.Shipments',
                icon: 'project',
                type: NAV_ITEM_TYPE_COLLAPSE,
                authority: [ADMIN, USER],
                subMenu: [

                    // {
                    //     key: 'appsshipment.allshipment',
                    //     path: `${APP_PREFIX_PATH}/shipmennt/allshipment`,
                    //     title: 'Allshipment',
                    //     translateKey: 'nav.shipmennt.allshipment',
                    //     icon: '',
                    //     type: NAV_ITEM_TYPE_ITEM,
                    //     authority: [ADMIN, USER],
                    //     subMenu: [],
                    // },
                    // {
                    //     key: 'appsSales.dashboard',
                    //     path: `${APP_PREFIX_PATH}/sales/dashboard`,
                    //     title: 'Dashboard',
                    //     translateKey: 'nav.appsSales.dashboard',
                    //     icon: '',
                    //     type: NAV_ITEM_TYPE_ITEM,
                    //     authority: [ADMIN, USER],
                    //     subMenu: [],
                    // },
                    // {
                    //     key: 'appsSales.productList',
                    //     path: `${APP_PREFIX_PATH}/sales/product-list`,
                    //     title: 'Product List',
                    //     translateKey: 'nav.appsSales.productList',
                    //     icon: '',
                    //     type: NAV_ITEM_TYPE_ITEM,
                    //     authority: [ADMIN, USER],
                    //     subMenu: [],
                    // },

                     // Shipmemt route Start ...

                     
                    {
                        key: 'allshipment',
                        path: `${APP_PREFIX_PATH}/shipment/allshipment`,
                        title: 'All Shipment',
                        translateKey: '',
                        icon: '',
                        type: NAV_ITEM_TYPE_ITEM,
                        authority: [ADMIN, USER],
                        subMenu: [],
                    },

                    {
                        key: 'shipment',
                        path: `${APP_PREFIX_PATH}/shipment/create-shipment`,
                        title: 'Create Shipment',
                        translateKey: '',
                        icon: '',
                        type: NAV_ITEM_TYPE_ITEM,
                        authority: [ADMIN, USER],
                        subMenu: [],
                    },


                    {
                        key: 'pickuprequest',
                        path: `${APP_PREFIX_PATH}/shipment/pickuprequest`,
                        title: 'Pickup Requesr',
                        translateKey: '',
                        icon: '',
                        type: NAV_ITEM_TYPE_ITEM,
                        authority: [ADMIN, USER],
                        subMenu: [],
                    },
                    // {
                    //     key: 'appsSales.productEdit',
                    //     path: `${APP_PREFIX_PATH}/sales/product-edit/12`,
                    //     title: 'Product Edit',
                    //     translateKey: 'nav.appsSales.productEdit',
                    //     icon: '',
                    //     type: NAV_ITEM_TYPE_ITEM,
                    //     authority: [ADMIN, USER],
                    //     subMenu: [],
                    // },
                    // {
                    //     key: 'appsSales.productNew',
                    //     path: `${APP_PREFIX_PATH}/sales/product-new`,
                    //     title: 'New Product',
                    //     translateKey: 'nav.appsSales.productNew',
                    //     icon: '',
                    //     type: NAV_ITEM_TYPE_ITEM,
                    //     authority: [ADMIN, USER],
                    //     subMenu: [],
                    // },
                    // {
                    //     key: 'appsSales.orderList',
                    //     path: `${APP_PREFIX_PATH}/sales/order-list`,
                    //     title: 'Order List',
                    //     translateKey: 'nav.appsSales.orderList',
                    //     icon: '',
                    //     type: NAV_ITEM_TYPE_ITEM,
                    //     authority: [ADMIN, USER],
                    //     subMenu: [],
                    // },
                    // {
                    //     key: 'appsSales.orderDetails',
                    //     path: `${APP_PREFIX_PATH}/sales/order-details/95954`,
                    //     title: 'Order Details',
                    //     translateKey: 'nav.appsSales.orderDetails',
                    //     icon: '',
                    //     type: NAV_ITEM_TYPE_ITEM,
                    //     authority: [ADMIN, USER],
                    //     subMenu: [],
                    // },
                ],
            },

            // werehouse
            {
                key: 'werehouse',
                path: `${APP_PREFIX_PATH}/werehouse/werehouse`,
                title: 'Warehouse',
                translateKey: '',
                icon: 'apps',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [ADMIN, USER],
                subMenu: [],
            },



            // {
            //      key: 'AddWarehouse',
            //      path: `${APP_PREFIX_PATH}/AddWarehouse/AddWarehouse`,
            //      title: 'Add Warehouse',
            //      translateKey: '',
            //      icon: '',
            //      type: NAV_ITEM_TYPE_ITEM,
            //      authority: [ADMIN, USER],
            //      subMenu: [],
            //  },

             
            // {
            //     key: 'Warehouse',
            //     path: '',
            //     title: 'Warehouse',
            //     translateKey: 'nav.Warehouse.Warehouse',
            //     icon: 'apps',
            //     type: NAV_ITEM_TYPE_COLLAPSE,
            //     authority: [ADMIN, USER],
            //     subMenu: [
                   

                   
            //         {
            //             key: 'AddWarehouse',
            //             path: `${APP_PREFIX_PATH}/AddWarehouse/AddWarehouse`,
            //             title: 'Add Warehouse',
            //             translateKey: '',
            //             icon: '',
            //             type: NAV_ITEM_TYPE_ITEM,
            //             authority: [ADMIN, USER],
            //             subMenu: [],
            //         },
            //     ],
            // },

            {
                key: 'apps.Billing',
                path: '',
                title: 'Billing',
                translateKey: 'nav.appsBilling.Billing',
                icon: 'crypto',
                type: NAV_ITEM_TYPE_COLLAPSE,
                authority: [ADMIN, USER],
                subMenu: [
                    {
                        key: 'appsknowledgeBase.helpCenter',
                        path: `${APP_PREFIX_PATH}/knowledge-base/help-center`,
                        title: 'Help Center',
                        translateKey: 'nav.appsknowledgeBase.helpCenter',
                        icon: '',
                        type: NAV_ITEM_TYPE_ITEM,
                        authority: [ADMIN, USER],
                        subMenu: [],
                    },
                    {
                        key: 'appsknowledgeBase.article',
                        path: `${APP_PREFIX_PATH}/knowledge-base/article?id=rZjCbSyae5`,
                        title: 'Article',
                        translateKey: 'nav.appsknowledgeBase.article',
                        icon: '',
                        type: NAV_ITEM_TYPE_ITEM,
                        authority: [ADMIN, USER],
                        subMenu: [],
                    },
                    {
                        key: 'appsknowledgeBase.manageArticles',
                        path: `${APP_PREFIX_PATH}/knowledge-base/manage-articles`,
                        title: 'Manage Articles',
                        translateKey: 'nav.appsknowledgeBase.manageArticles',
                        icon: '',
                        type: NAV_ITEM_TYPE_ITEM,
                        authority: [ADMIN, USER],
                        subMenu: [],
                    },
                    {
                        key: 'appsknowledgeBase.editArticle',
                        path: `${APP_PREFIX_PATH}/knowledge-base/edit-article?id=rZjCbSyae5&categoryLabel=Survey&categoryValue=survey`,
                        title: 'Edit Article',
                        translateKey: 'nav.appsknowledgeBase.editArticle',
                        icon: '',
                        type: NAV_ITEM_TYPE_ITEM,
                        authority: [ADMIN, USER],
                        subMenu: [],
                    },
                ],
            },
            {
                key: 'apps.Setup and Manage',
                path: '',
                title: 'Setup and Manage',
                translateKey: 'nav.appsSetup and Manage.Setup and Manage',
                icon: 'crm',
                type: NAV_ITEM_TYPE_COLLAPSE,
                authority: [ADMIN, USER],
                subMenu: [
                    {
                        key: 'appsAccount.settings',
                        path: `${APP_PREFIX_PATH}/account/settings/profile`,
                        title: 'Settings',
                        translateKey: 'nav.appsAccount.settings',
                        icon: '',
                        type: NAV_ITEM_TYPE_ITEM,
                        authority: [ADMIN, USER],
                        subMenu: [],
                    },
                    {
                        key: 'appsAccount.invoice',
                        path: `${APP_PREFIX_PATH}/account/invoice/36223`,
                        title: 'Invoice',
                        translateKey: 'nav.appsAccount.invoice',
                        icon: '',
                        type: NAV_ITEM_TYPE_ITEM,
                        authority: [ADMIN, USER],
                        subMenu: [],
                    },
                    {
                        key: 'appsAccount.activityLog',
                        path: `${APP_PREFIX_PATH}/account/activity-log`,
                        title: 'Activity Log',
                        translateKey: 'nav.appsAccount.activityLog',
                        icon: '',
                        type: NAV_ITEM_TYPE_ITEM,
                        authority: [ADMIN, USER],
                        subMenu: [],
                    },
                    {
                        key: 'appsAccount.kycForm',
                        path: `${APP_PREFIX_PATH}/account/kyc-form`,
                        title: 'KYC Form',
                        translateKey: 'nav.appsAccount.kycForm',
                        icon: '',
                        type: NAV_ITEM_TYPE_ITEM,
                        authority: [ADMIN, USER],
                        subMenu: [],
                    },
                ],
            },
            {
                key: 'apps.Tools',
                path: '',
                title: 'Tools',
                translateKey: 'nav.appsTools.Tools',
                icon: 'account',
                type: NAV_ITEM_TYPE_COLLAPSE,
                authority: [ADMIN, USER],
                subMenu: [
                    {
                        key: 'appsAccount.settings',
                        path: `${APP_PREFIX_PATH}/account/settings/profile`,
                        title: 'Settings',
                        translateKey: 'nav.appsAccount.settings',
                        icon: '',
                        type: NAV_ITEM_TYPE_ITEM,
                        authority: [ADMIN, USER],
                        subMenu: [],
                    },
                    {
                        key: 'appsAccount.invoice',
                        path: `${APP_PREFIX_PATH}/account/invoice/36223`,
                        title: 'Invoice',
                        translateKey: 'nav.appsAccount.invoice',
                        icon: '',
                        type: NAV_ITEM_TYPE_ITEM,
                        authority: [ADMIN, USER],
                        subMenu: [],
                    },
                    {
                        key: 'appsAccount.activityLog',
                        path: `${APP_PREFIX_PATH}/account/activity-log`,
                        title: 'Activity Log',
                        translateKey: 'nav.appsAccount.activityLog',
                        icon: '',
                        type: NAV_ITEM_TYPE_ITEM,
                        authority: [ADMIN, USER],
                        subMenu: [],
                    },
                    {
                        key: 'appsAccount.kycForm',
                        path: `${APP_PREFIX_PATH}/account/kyc-form`,
                        title: 'KYC Form',
                        translateKey: 'nav.appsAccount.kycForm',
                        icon: '',
                        type: NAV_ITEM_TYPE_ITEM,
                        authority: [ADMIN, USER],
                        subMenu: [],
                    },
                ],
            },

            // Help and Support

            {
                key: 'Help and Support',
                path: `${APP_PREFIX_PATH}/account/kyc-form`,
                title: 'Help and Support',
                translateKey: 'nav.Help and Support',
                icon: 'knowledgeBase',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [ADMIN, USER],
                subMenu: [],
            },
        ],
    },
]

export default appsNavigationConfig
